{1}{}{PID_PURPLE_ROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. В качестве красителя подойдёт цветок брока.@@SK_OUTDOORSMAN 40@PID_RAGS 5&PID_POCKET_LINT 2&PID_BROC_FLOWER 5&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_PURPLE_ROBE 1@exp 150 script fix_boy@fix_Repair}
{2}{}{PID_LEATHER_JACKET@Сшейте куртку из шкурок, а затем замочите в красящем растворе.@@SK_OUTDOORSMAN 40@PID_GECKO_PELT 6&PID_POCKET_LINT 2&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_SHIV 1@PID_LEATHER_JACKET 1@exp 150 script fix_boy@fix_Repair}
{3}{}{PID_LEATHER_ARMOR@Шкуры брамина, сшитые в несколько слоёв, позволят чувствовать себя защищённей.@SK_OUTDOORSMAN 30&SK_REPAIR 20@SK_OUTDOORSMAN 60&SK_REPAIR 40&ST_STRENGTH 6@PID_BRAHMIN_SKIN 2&PID_POCKET_LINT 1&PID_ROPE 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_LEATHER_ARMOR 1@exp 100 script fix_boy@fix_Repair}
{4}{}{PID_LEATHER_ARMOR_MK_II@Укрепите броню несколькими слоями кожи и обработайте её химикатами для улучшения защитных свойств.@SK_OUTDOORSMAN 30&SK_REPAIR 40@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_LEATHER_ARMOR 1&PID_ROPE 1&PID_GOLDEN_GECKO_PELT 2&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LEATHER_ARMOR_MK_II 1@exp 100 script fix_boy@fix_Advanced}
{5}{}{PID_CURED_LEATHER_ARMOR@Если на горизонте показались проблемы, то лучше забыть про стиль и укрепить свою старую добрую куртку ещё десятком слоёв кожи.@SK_OUTDOORSMAN 50&SK_REPAIR 50@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_LEATHER_JACKET 1&PID_BRAHMIN_SKIN 2&PID_GOLDEN_GECKO_PELT 1&PID_POCKET_LINT 2@PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR 1@exp 150 script fix_boy@fix_Advanced}
{6}{}{PID_METAL_ARMOR@Боитесь ножей из-за угла и когтей гекко? С вашей новой металлической бронёй они будут для вас не больше, чем царапинами.@SK_REPAIR 40@SK_REPAIR 80@PID_METAL_TRASH 5&PID_PUMP_PARTS 2&PID_LEATHER_ARMOR 1&PID_POCKET_LINT 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR 1@exp 150 script fix_boy@fix_Advanced}
{7}{}{PID_METAL_ARMOR_MK_II@Укрепите слабые места на броне, а затем обработайте напильником и отполируйте до блеска для лучше защиты от лазерного оружия.@SK_REPAIR 60@SK_REPAIR 100@PID_METAL_ARMOR 1&PID_METAL_TRASH 2&PID_MOUSE_SKIN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR_MK_II 1@exp 100 script fix_boy@fix_Advanced}
{8}{}{PID_RING_BOXING_GLOVES@Сшейте шкуры и набейте их мягким мусором.@SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 40@PID_GECKO_PELT 2&PID_POCKET_LINT 4@PID_SHIV 1@PID_RING_BOXING_GLOVES 1@exp 50 script fix_boy@fix_Repair}
{9}{}{PID_RING_PLATED_BOXING_GLOVES@Перчатки с утяжелителем - правильный выбор для участника подпольных боёв. Главное - не оставляйте их без присмотра в раздевалке.@SK_REPAIR 20&SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 50&SK_REPAIR 30@PID_RING_BOXING_GLOVES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_RING_PLATED_BOXING_GLOVES 1@exp 50 script fix_boy@fix_Repair}
{10}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 50@PID_METAL_TRASH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_BRASS_KNUCKLES 1@exp 50 script fix_boy@fix_Repair}
{11}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету, четыре дырки в противнике того стоят.@SK_REPAIR 40@SK_REPAIR 55@PID_BRASS_KNUCKLES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SPIKED_KNUCKLES 1@exp 100 script fix_boy@fix_Repair}
{13}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, обмотать рукоять кожей, и этот нож уже можно называть оружием.@SK_REPAIR 60@SK_OUTDOORSMAN 20&SK_REPAIR 80&SK_UNARMED 60@PID_KNIFE 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_COMBAT_KNIFE 1@exp 100 script fix_boy@fix_Repair}
{14}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_PUMP_PARTS 1&PID_FIREWOOD 1@@PID_SLEDGEHAMMER 1@exp 50 script fix_boy@fix_Repair}
{15}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 30&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@exp 50 script fix_boy@fix_Repair}
{16}{}{PID_SHARP_SPEAR@Заточка копья кремнем от фирмы "Морлис" позволит разрубать врагов им как алебардой.@SK_OUTDOORSMAN 30@SK_MELEE_WEAPONS 40&SK_REPAIR 20&SK_OUTDOORSMAN 40@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@exp 50 script fix_boy@fix_Repair}
{17}{}{PID_SHARPENED_POLE@Вжик-вжик, готово!@@SK_OUTDOORSMAN 20@PID_FIREWOOD 1@PID_KNIFE 1@PID_SHARPENED_POLE 1@exp 10 }
{18}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@exp 50 script fix_boy@fix_Repair}
{19}{}{PID_WRENCH@Найдите железку подходящего размера и выпилите из неё нечто, чем можно было бы откручивать гайки.@@SK_REPAIR 50@PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_SLEDGEHAMMER 1|PID_SUPER_TOOL_KIT 1@PID_WRENCH 1@exp 50 script fix_boy@fix_Repair}
{20}{}{PID_KNIFE@Заточите железяку о камень, обмотайте конец какой-нибудь тряпкой. Готово, можно идти похвастаться родителям.@@SK_OUTDOORSMAN 20@PID_METAL_TRASH 1&PID_RAGS 1@@PID_KNIFE 1@exp 50 script fix_boy@fix_Repair}
{21}{}{PID_CLUB@Отломайте нахрен минимум треть этой палки, забейте камнем в один конец какой-нибудь утяжелитель. Отломаный кусок можно притарабанить в качестве дополнительной рукояти. Готово, можно пойти проломить кому-нибудь черепушку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40&SK_REPAIR 30@PID_SHARPENED_POLE 1&PID_PUMP_PARTS 1@PID_ROCK 1@PID_CLUB 1@exp 50 script fix_boy@fix_Repair}
{22}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_KNIFE 1@PID_SHIV 1@exp 50 script fix_boy@fix_Repair}
{23}{}{PID_THROWING_KNIFE@Сбалансируйте и дополнительно заточите эту железку.@SK_THROWING 40@SK_THROWING 50&SK_REPAIR 30@PID_KNIFE 1&PID_FLINT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_THROWING_KNIFE 1@exp 50 script fix_boy@fix_Repair}
{24}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 30@PID_ROT_GUT 1&PID_RAGS 1&PID_BROC_FLOWER 5@@PID_MOLOTOV_COCKTAIL 1@exp 50 script fix_boy@fix_Science}
{25}{}{PID_MOLOTOV_COCKTAIL@Нет огнемёта? Не беда, всегда можно найти способ доставить пламя до противника.@SK_SCIENCE 20@SK_SCIENCE 30&SK_REPAIR 30@PID_BOTTLE_GLASS 1&PID_RAGS 1&PID_FLAMETHROWER_FUEL 1@@PID_MOLOTOV_COCKTAIL 1@exp 50 script fix_boy@fix_Science}
{26}{}{PID_SCOPED_HUNTING_RIFLE@Для простенького прицела сойдут и линзы из чьих-нибудь очков, главное - чётко следовать инструкциям.@SK_SMALL_GUNS 50@SK_REPAIR 60&SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_HUNTING_RIFLE 1&PID_TUBE 1&PID_SPECTACLES 2&PID_PUMP_PARTS 1@PID_GUNS_AND_BULLETS 1&PID_SUPER_TOOL_KIT 1@PID_SCOPED_HUNTING_RIFLE 1@exp 100 script fix_boy@fix_Advanced}
{27}{}{PID_ASSAULT_RIFLE_EXT_MAG@Изготовьте новый магазин и найдите в мусоре для него пружину помощнее.@SK_SMALL_GUNS 50@SK_REPAIR 100@PID_ASSAULT_RIFLE 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 1@PID_SUPER_TOOL_KIT 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 60 script fix_boy@fix_Advanced}
{28}{}{PID_SHOTGUN@Найдите две трубы более-менее подходящего диаметра, изготовьте к ним приклад и простенький спусковой механизм.@SK_SMALL_GUNS 50@SK_SMALL_GUNS 80&SK_REPAIR 80@PID_SHOTGUN_SHELLS 20&PID_TUBE 2&PID_FIREWOOD 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 2@PID_SUPER_TOOL_KIT 1&PID_COMBAT_KNIFE 1&PID_GUNS_AND_BULLETS 1@PID_SHOTGUN 1@exp 150 script fix_boy@fix_Repair}
{29}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 20@SK_REPAIR 30@PID_SHOTGUN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SAWED_OFF_SHOTGUN 1@exp 100 script fix_boy@fix_Repair}
{30}{}{PID_SHOTGUN_SHELLS@Вроде бы всё выглядит не так уж и сложно.@SK_SCIENCE 10@SK_SCIENCE 15&SK_SMALL_GUNS 50&SK_REPAIR 25@PID_GUNPOWDER 2&PID_REAL_BOTTLE_CAPS 20&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1@PID_SHOTGUN_SHELLS 20@exp 100 script fix_boy@fix_Advanced}
{31}{}{PID_DESERT_EAGLE_EXT_MAG@С переделкой магазина придётся помучиться, но она сэкономит несколько драгоценных секунд в бою.@SK_REPAIR 60@SK_REPAIR 80@PID_DESERT_EAGLE 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 60 script fix_boy@fix_Advanced}
{32}{}{PID_SPRINGER_RIFLE@Главной проблемой будет найти трубу подходящего диаметра, а спусковой механизм вы соорудить сумеете.@SK_SMALL_GUNS 50@SK_REPAIR 40&SK_OUTDOORSMAN 40&SK_SMALL_GUNS 50@PID_TUBE 1&PID_FIREWOOD 1&PID_10MM_JHP 5&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SPRINGER_RIFLE 1@exp 100 script fix_boy@fix_Repair}
{33}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@SK_SMALL_GUNS 50@SK_OUTDOORSMAN 30&SK_REPAIR 40@PID_PUMP_PARTS 3&PID_FIREWOOD 1&PID_10MM_JHP 3@@PID_ZIP_GUN 1@exp 75 script fix_boy@fix_Repair}
{34}{}{PID_FN_FAL_HPFA@Пускай отдача будет ломать вам плечо, но это улучшение того стоит.@SK_REPAIR 100@SK_SMALL_GUNS 80&SK_REPAIR 120&SK_SCIENCE 80@PID_FN_FAL 1&PID_METAL_TRASH 1@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_FN_FAL_HPFA 1@exp 120 script fix_boy@fix_HighTech}
{35}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_REPAIR 90@SK_REPAIR 100&SK_SCIENCE 60@PID_FLAMETHROWER_FUEL 5&PID_METAL_TRASH 3&PID_TUBE 1&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMER 1@exp 150 script fix_boy@fix_HighTech}
{36}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 80@PID_FLAMETHROWER_FUEL 1&PID_CHEMICALS 1&PID_PUMP_PARTS 2&PID_ROT_GUT 1@@PID_FLAMETHROWER_FUEL 5@exp 50 script fix_boy@fix_Advanced}
{37}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_RAGS 1@PID_ROCK 1@PID_HEALING_POWDER 1@exp 50 script fix_boy@fix_Science}
{38}{}{PID_ANTIDOTE@Это будет скорей самовнушением. @SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 40&SK_DOCTOR 20@PID_BOOZE 1&PID_SCORPION_TAIL 1@PID_LIGHTER 1@PID_ANTIDOTE 1@exp 50 script fix_boy@fix_Science}
{39}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле.@SK_LOCKPICK 50@SK_LOCKPICK 70@PID_METAL_TRASH 1&PID_PUMP_PARTS 1&PID_GECKO_PELT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_LOCKPICKS 1@exp 50 script fix_boy@fix_Repair}
{40}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами!@SK_LOCKPICK 70@SK_LOCKPICK 100@PID_LOCKPICKS 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_EXP_LOCKPICK_SET 1@exp 100 script fix_boy@fix_Repair}
{41}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Схема простейшего приёмника в каждом номере "Электроники Дина"!@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1|PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@exp 100 }
{42}{}{PID_FIRST_AID_KIT@Бинты, спирт для промывки ран и другие полезные вещи в сумке из кожи многострадального гекко.@SK_FIRST_AID 50@SK_DOCTOR 50&SK_FIRST_AID 60&SK_SCIENCE 20@PID_RAGS 5&PID_BOOZE 1&PID_ANTIDOTE 1&PID_GECKO_PELT 1&PID_POCKET_LINT 1@@PID_FIRST_AID_KIT 1@exp 150 }
{43}{}{PID_RADIO@Почините радио с использованием деталей со старых микросхем.@SK_REPAIR 50@SK_REPAIR 60@PID_VIC_RADIO 1&PID_V15_COMPUTER_PART 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_RADIO 1@exp 100 script fix_boy@fix_Repair}
{44}{}{PID_TNT@Вливайте азотную кислоту в толуол, постоянно нагревая, осадок просушите и поместите в какую-нибудь банку.@SK_SCIENCE 80@SK_SCIENCE 100@PID_CHEMICALS 2&PID_BOTTLE_FULL 1&PID_PUMP_PARTS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_TNT 1@exp 100 script fix_boy@fix_Science}
{45}{}{PID_FRAG_GRENADE@Поместите взрывчатое вещевство в осколочную рубашку и придумайте простенький взрыватель.@SK_REPAIR 80@SK_REPAIR 100@PID_PUMP_PARTS 1&PID_METAL_TRASH 1&PID_TNT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_FRAG_GRENADE 1@exp 130 script fix_boy@fix_Advanced}
{46}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 90@SK_SCIENCE 110&SK_OUTDOORSMAN 50@PID_MEAT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_CHEMISTRY_MANUAL 1@PID_NITROGLYCERIN 1@exp 150 script fix_boy@fix_Science}
{47}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@SK_TRAPS 100@SK_OUTDOORSMAN 30&SK_SCIENCE 60&SK_TRAPS 120&SK_REPAIR 100@PID_NITROGLYCERIN 2&PID_HEALING_POWDER 2&PID_FIREWOOD 1&PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_DYNAMITE 1@exp 200 script fix_boy@fix_HighTech}
{48}{}{PID_GUNPOWDER@Используйте кислоту для получения калийной селитры, смешайте 6 частей селитры с 1 частью угля и 1 серы.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 50&SK_SCIENCE 80@PID_MINERAL 1&PID_CHEMICALS 1&PID_FIREWOOD 1@PID_CHEMISTRY_MANUAL 1&PID_ROCK 1@PID_GUNPOWDER 1@exp 100 script fix_boy@fix_Science}
{49}{}{PID_HEXOGEN@Получите нитрат аммония смешиванием собственной мочи с азотной кислотой и выпариванием. Добавьте толчёный буффаут. Залейте второй частью кислоты, охлаждайте, процедите осадок.@SK_SCIENCE 100@SK_SCIENCE 120&SK_OUTDOORSMAN 60@PID_BUFFOUT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 2&PID_RAGS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_HEXOGEN 1@exp 150 script fix_boy@fix_Science}
{50}{}{PID_PLASTIC_EXPLOSIVES_DULL@Найдите в мусоре какой-нибудь пластик, нагрейте его до плавления и вмешивайте в него порошок гексогена. Всё, теперь он удобен для хранения.@SK_SCIENCE 120@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_PUMP_PARTS 2&PID_HEXOGEN 1@PID_LIGHTER 1@PID_PLASTIC_EXPLOSIVES_DULL 1@exp 100 script fix_boy@fix_Advanced}
{51}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор из запчастей и старого радио.@SK_REPAIR 100@SK_REPAIR 130&SK_TRAPS 120@PID_PLASTIC_EXPLOSIVES_DULL 1&PID_V15_COMPUTER_PART 1&PID_RADIO 1@PID_MULTI_TOOL 1&PID_CHEMISTRY_MANUAL 1|PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_PLASTIC_EXPLOSIVES 1@exp 200 script fix_boy@fix_HighTech}
{52}{}{PID_MINE@Высыпьте гексоген в какую-нибудь старую банку, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@SK_TRAPS 80@SK_TRAPS 130&SK_SCIENCE 100&SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_HEXOGEN 1&PID_PUMP_PARTS 2&PID_SHOTGUN_SHELLS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_MINE 1@exp 200 script fix_boy@fix_HighTech}
{53}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_CHEMICALS 2&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMETHROWER_FUEL 10@exp 50 script fix_boy@fix_Advanced}
{54}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@SK_FIRST_AID 30@SK_FIRST_AID 70&SK_SCIENCE 70@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1&PID_BOOZE 1&PID_HEALING_POWDER 2@PID_LIGHTER 1&PID_FIRST_AID_BOOK 1&PID_CHEMISTRY_MANUAL 1&PID_FIRST_AID_KIT 1@PID_STIMPAK 1@exp 50 script fix_boy@fix_Science}
{55}{}{PID_MAUSER_SMG@В одном из номеров журнала "Пушки и пули" была опубликована схема автоматического Маузера М712 калибра 7,62. Изучив её, вы поняли, что 9мм Маузер можно было бы переделать подобным образом.@SK_SMALL_GUNS 50@SK_REPAIR 50@PID_9MM_MAUSER 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1|PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_MAUSER_SMG 1@exp 100 script fix_boy@fix_Repair}
{56}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_ROCK 1@PID_AXE 1@exp 50 script fix_boy@fix_Repair}
{57}{}{PID_MEDICAL_SUPPLIES@Алкоголь для дезинфекции, лечебный порошок для лечения - и вот у вас уже неплохой комплект для оказания первой помощи в условиях пустоши. Эффективность близка к волшебным микстурам времён Дикого Запада, но от укусов и ран помогает.@SK_FIRST_AID 20@SK_FIRST_AID 30@PID_BOOZE 1&PID_HEALING_POWDER 1@@PID_MEDICAL_SUPPLIES 3@exp 50 script fix_boy@fix_Science}
{58}{}{PID_14MM_AP@Выглядит не сложнее патронов для дробовика.@SK_SCIENCE 10@SK_SCIENCE 15&SK_SMALL_GUNS 50&SK_REPAIR 25@PID_GUNPOWDER 2&PID_PUMP_PARTS 2&PID_REAL_BOTTLE_CAPS 12@PID_SUPER_TOOL_KIT 1@PID_14MM_AP 12@exp 100 script fix_boy@fix_Advanced}
{59}{}{PID_223_FMJ@Как оказалось, не нужно быть мастером для того, чтобы делать боеприпасы.@SK_SCIENCE 10@SK_SCIENCE 15&SK_SMALL_GUNS 50&SK_REPAIR 25@PID_GUNPOWDER 1&PID_PUMP_PARTS 2&PID_REAL_BOTTLE_CAPS 10@PID_SUPER_TOOL_KIT 1@PID_223_FMJ 10@exp 100 script fix_boy@fix_Advanced}
{60}{}{PID_10MM_JHP@Оказывается, довольно просто изготовить самые популярные патроны - 10 мм.@SK_SCIENCE 15@SK_SCIENCE 20&SK_SMALL_GUNS 50&SK_REPAIR 30@PID_GUNPOWDER 3&PID_PUMP_PARTS 2&PID_REAL_BOTTLE_CAPS 30@PID_SUPER_TOOL_KIT 1@PID_10MM_JHP 30@exp 120 script fix_boy@fix_Advanced}
{61}{}{PID_44_MAGNUM_JHP@Довольно мощный боеприпас. Как оказалось, его можно изготовить самостоятельно, имея необходимые навыки.@SK_SCIENCE 15@SK_SCIENCE 20&SK_SMALL_GUNS 50&SK_REPAIR 40@PID_GUNPOWDER 2&PID_PUMP_PARTS 2&PID_REAL_BOTTLE_CAPS 10@PID_SUPER_TOOL_KIT 1@PID_44_MAGNUM_JHP 10@exp 150 script fix_boy@fix_Advanced}
{62}{}{PID_DEFIB@Стандартный реанимационный набор для восстановления жизнедеятельности. Можно собрать, имея нужные познания в медицине@SK_DOCTOR 30@SK_FIRST_AID 50&SK_SCIENCE 40&SK_DOCTOR 70&SK_REPAIR 30@PID_METAL_TRASH 2&PID_SMALL_ENERGY_CELL 5&PID_PUMP_PARTS 2&PID_DOCTORS_BAG 1&PID_STIMPAK 2&PID_V15_COMPUTER_PART 1@PID_SUPER_TOOL_KIT 1@PID_DEFIB 1@exp 300 script fix_boy@fix_HighTech}
{63}{}{PID_LASER_PISTOL@Энергетическое оружие. Не очень мощное, но относительно простое в производстве.@SK_REPAIR 60@SK_REPAIR 100&SK_SCIENCE 120&SK_ENERGY_WEAPONS 80@PID_METAL_TRASH 2&PID_SMALL_ENERGY_CELL 5&PID_PUMP_PARTS 2&PID_SPECTACLES 1&PID_ZIP_GUN 1&PID_V15_COMPUTER_PART 2@PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_LASER_PISTOL 1@exp 500 script fix_boy@fix_HighTech}
{64}{}{PID_NEEDLER_PISTOL@Пистолет, стреляющий шприцами-дротиками. Вполне можно изготовить из подручных материалов.@SK_REPAIR 60@SK_REPAIR 100&SK_SCIENCE 120&SK_SMALL_GUNS 60@PID_METAL_TRASH 2&PID_HN_NEEDLER_CARTRIDGE 5&PID_PUMP_PARTS 3&PID_ZIP_GUN 1&PID_V15_COMPUTER_PART 1@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_NEEDLER_PISTOL 1@exp 500 script fix_boy@fix_HighTech}
{65}{}{PID_HN_NEEDLER_CARTRIDGE@Шприцы-дротики для пистолета-инъектора делаются из твердого пластика. Довольно просто. Нужно только заполнить их какими-нибудь химикатами.@SK_REPAIR 20@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_PUMP_PARTS 5@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_LIGHTER 1@PID_HN_NEEDLER_CARTRIDGE 10@exp 200 script fix_boy@fix_Advanced}
{66}{}{PID_NEED_CART_POISON@Картриджи для инъектора можно заполнить ядом радскорпионов. Измельчить 2 хвоста радскорпиона, залить растворителем, дать настояться несколько часов. Затем выпарить для достижения большей концентрации и заправить картриджи.@SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 100&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_HN_NEEDLER_CARTRIDGE 10&PID_METAL_TRASH 1&PID_SCORPION_TAIL 2@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_NEED_CART_POISON 10@exp 250 script fix_boy@fix_Advanced}
{67}{}{PID_HYPO_POISON@Сильнейший нейротоксин, который в малых количествах содержится в ядовитом жале радскорпионов можно извлечь методом кислотно-щелочной экстракции.@SK_SCIENCE 80@SK_SCIENCE 140@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 1&PID_BOTTLE_GLASS 2&PID_SCORPION_TAIL 8@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_HYPO_POISON 1@exp 350 script fix_boy@fix_Science}
{68}{}{PID_NEED_CART_NT@Картриджи иньектора можно заполнить опаснейшим нейротоксином... Нужно только найти нейротоксин. @SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_HYPO_POISON 1&PID_HN_NEEDLER_CARTRIDGE 10@@PID_NEED_CART_NT 10@exp 400 script fix_boy@fix_Advanced}
{69}{}{PID_PART_OF_ROPE@Возьмите что-нибудь острое и разрежьте веревку на несколько кусков. @SK_MELEE_WEAPONS 10@SK_MELEE_WEAPONS 20@PID_ROPE 1@PID_KNIFE 1|PID_SWITCHBLADE 1|PID_LIL_JESUS_WEAPON 1|PID_WAKIZASHI_BLADE 1|PID_AXE 1@PID_PART_OF_ROPE 10@exp 10 script fix_boy@fix_Repair}
{70}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@@@PID_PART_OF_ROPE 20@@PID_ROPE 1@exp 30 script fix_boy@fix_Repair}
{71}{}{PID_ANTIDOTE_2@Мощное противоядие, нейтрализующее действие нейротоксина. Можно сделать, имея образец токсина.@SK_SCIENCE 60@SK_SCIENCE 100@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 3&PID_BOTTLE_GLASS 2&PID_HYPO_POISON 1@PID_CHEMISTRY_MANUAL 1&PID_LIGHTER 1@PID_ANTIDOTE_2 3@exp 450 script fix_boy@fix_Science}
{72}{}{PID_HANDCUFFS@В довоенном журнале про оружие вы нашли статью об устройстве наручников. Не так уж сложно сделать, если немного рабираться в ремонте и замках.@SK_REPAIR 80@SK_SCIENCE 60&SK_REPAIR 100&SK_LOCKPICK 100@PID_METAL_TRASH 3&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_WELDING 1@PID_HANDCUFFS 1@exp 100 script fix_boy@fix_Repair}
{73}{}{PID_HANDCUFFS@Сломанные наручники можно восстановить и переделать под новый ключ, если под рукой есть нужны инструменты@SK_REPAIR 40@SK_REPAIR 60&SK_LOCKPICK 40@PID_METAL_TRASH 1&PID_BROKEN_CUFFS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_HANDCUFFS 1@exp 50 script fix_boy@fix_Repair}
{74}{}{PID_COLT@Листая довоенный журнал про оружие, вы нашли схему Кольта М1911. С немалым удивлением, вы обнаружили, что под него довольно просто переделать обычный 10мм пистолет!@SK_REPAIR 80@SK_REPAIR 100&SK_SMALL_GUNS 120@PID_10MM_PISTOL 1&PID_METAL_TRASH 1&PID_TUBE 1&PID_PUMP_PARTS 2&PID_45_CALIBER_AMMO 7@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_COLT 1@exp 450 script fix_boy@fix_Advanced}
{75}{}{PID_MUMARMOR@Специализированная броня для супермутантов. Укрепляет их и без того мощное тело.@SK_REPAIR 80@SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_METAL_TRASH 8&PID_GOLDEN_GECKO_PELT 4&PID_PUMP_PARTS 2&PID_WELDING 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUMARMOR 1@exp 550 script fix_boy@fix_Advanced}
{76}{}{PID_MUJACKET@Кожанная куртка для мутантов. Технология производста почти не отличается от обычной, но материала уходит в два раза больше.@SK_OUTDOORSMAN 40@SK_REPAIR 80&SK_OUTDOORSMAN 80@PID_GECKO_PELT 4&PID_GOLDEN_GECKO_PELT 8&PID_POCKET_LINT 4&PID_CHEMICALS 2@PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUJACKET 1@exp 250 script fix_boy@fix_Advanced}
{77}{}{PID_SOUND_BLASTER@В довоенном журнале вы нашли статью об оглушающем акустическом оружии. Схема прилагается. Выглядит не слишком сложно.@SK_BIG_GUNS 80@SK_REPAIR 60&SK_BIG_GUNS 80&SK_SCIENCE 100@PID_METAL_TRASH 8&PID_PUMP_PARTS 4&PID_TUBE 1&PID_V15_COMPUTER_PART 2&PID_SPRINGER_RIFLE 1&PID_SMALL_ENERGY_CELL 10@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_SOUND_BLASTER 1@exp 600 script fix_boy@fix_HighTech}
{78}{}{PID_SANDROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава.@@SK_OUTDOORSMAN 40@PID_RAGS 5&PID_POCKET_LINT 2&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_SANDROBE 1@exp 150 script fix_boy@fix_Repair}
{79}{}{PID_CURED_LEATHER_ARMOR_MK_II@Хотите ещё более плотную куртку? Пожалуйста. Только учтите, что она не такая просторная, хоть и выглядит достаточно стильно.@SK_REPAIR 60&SK_OUTDOORSMAN 60@SK_OUTDOORSMAN 90&SK_REPAIR 75@PID_METAL_TRASH 2&PID_POCKET_LINT 2&PID_FIRE_GECKO_PELT 1&PID_CURED_LEATHER_ARMOR 1@PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR_MK_II 1@exp 185 script fix_boy@fix_Advanced}
{80}{}{PID_ONEHAND_ROCKET_LAUNCHER@Найдите трубу более-менее подходящего диаметра, изготовьте рукоять и простенький спусковой механизм. Соберите всё вместе и надейтесь, что оно будет работать.@SK_BIG_GUNS 80@SK_BIG_GUNS 130&SK_SCIENCE 50&SK_REPAIR 100@PID_FIREWOOD 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 6&PID_TUBE 1@PID_SUPER_TOOL_KIT 1&PID_COMBAT_KNIFE 1&PID_GUNS_AND_BULLETS 1@PID_ONEHAND_ROCKET_LAUNCHER 1@exp 240 script fix_boy@fix_Repair}
