{1}{}{PID_PURPLE_ROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. В качестве красителя подойдёт цветок брока.@@SK_OUTDOORSMAN 40@PID_RAGS 5&PID_POCKET_LINT 2&PID_BROC_FLOWER 5&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_PURPLE_ROBE 1@exp 150 script fix_boy@fix_Repair}
{2}{}{PID_LEATHER_JACKET@Сшейте куртку из шкурок, а затем замочите в красящем растворе.@@SK_OUTDOORSMAN 40@PID_GECKO_PELT 6&PID_POCKET_LINT 2&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_SHIV 1@PID_LEATHER_JACKET 1@exp 150 script fix_boy@fix_Repair}
{3}{}{PID_LEATHER_ARMOR@Шкуры брамина, сшитые в несколько слоёв, позволят чувствовать себя защищённей.@SK_OUTDOORSMAN 30&SK_REPAIR 20@SK_OUTDOORSMAN 60&SK_REPAIR 40&ST_STRENGTH 6@PID_BRAHMIN_SKIN 2&PID_POCKET_LINT 1&PID_ROPE 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_LEATHER_ARMOR 1@exp 100 script fix_boy@fix_Repair}
{4}{}{PID_LEATHER_ARMOR_MK_II@Укрепите броню несколькими слоями кожи и обработайте её химикатами для улучшения защитных свойств.@SK_OUTDOORSMAN 30&SK_REPAIR 40@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_LEATHER_ARMOR 1&PID_ROPE 1&PID_GOLDEN_GECKO_PELT 2&PID_CHEMICALS 1@PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LEATHER_ARMOR_MK_II 1@exp 100 script fix_boy@fix_Advanced}
{5}{}{PID_CURED_LEATHER_ARMOR@Если на горизонте показались проблемы, то лучше забыть про стиль и укрепить свою старую добрую куртку ещё десятком слоёв кожи. Шкуры огненных гекко послужат отличной защитой от огня.@SK_OUTDOORSMAN 50&SK_REPAIR 50@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_LEATHER_JACKET 1&PID_BRAHMIN_SKIN 2&PID_POCKET_LINT 2&PID_FIRE_GECKO_PELT 2@PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR 1@exp 150 script fix_boy@fix_Advanced}
{6}{}{PID_METAL_ARMOR@Боитесь ножей из-за угла и когтей гекко? С вашей новой металлической бронёй они будут для вас не больше, чем царапинами.@SK_REPAIR 40@SK_REPAIR 80@PID_METAL_TRASH 5&PID_PUMP_PARTS 2&PID_LEATHER_ARMOR 1&PID_POCKET_LINT 1&PID_IRON_PLATE 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR 1@exp 150 script fix_boy@fix_Advanced}
{7}{}{PID_METAL_ARMOR_MK_II@Укрепите слабые места на броне, а затем обработайте напильником и отполируйте до блеска для лучше защиты от лазерного оружия.@SK_REPAIR 60@SK_REPAIR 100@PID_METAL_ARMOR 1&PID_METAL_TRASH 2&PID_MOUSE_SKIN 1&PID_IRON_PLATE 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_METAL_ARMOR_MK_II 1@exp 100 script fix_boy@fix_Advanced}
{8}{}{PID_RING_BOXING_GLOVES@Сшейте шкуры и набейте их мягким мусором.@SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 40@PID_GECKO_PELT 2&PID_POCKET_LINT 4@PID_SHIV 1@PID_RING_BOXING_GLOVES 1@exp 50 script fix_boy@fix_Repair}
{9}{}{PID_RING_PLATED_BOXING_GLOVES@Перчатки с утяжелителем - правильный выбор для участника подпольных боёв. Главное - не оставляйте их без присмотра в раздевалке.@SK_REPAIR 20&SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 50&SK_REPAIR 30@PID_RING_BOXING_GLOVES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_RING_PLATED_BOXING_GLOVES 1@exp 50 script fix_boy@fix_Repair}
{10}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 50@PID_METAL_TRASH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_BRASS_KNUCKLES 1@exp 50 script fix_boy@fix_Repair}
{11}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету, четыре дырки в противнике того стоят.@SK_REPAIR 40@SK_REPAIR 55@PID_BRASS_KNUCKLES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SPIKED_KNUCKLES 1@exp 100 script fix_boy@fix_Repair}
{13}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, обмотать рукоять кожей, и этот нож уже можно называть оружием.@SK_REPAIR 60@SK_OUTDOORSMAN 20&SK_REPAIR 80&SK_MELEE_WEAPONS 60@PID_KNIFE 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_COMBAT_KNIFE 1@exp 100 script fix_boy@fix_Repair}
{14}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_PUMP_PARTS 1&PID_FIREWOOD 1@@PID_SLEDGEHAMMER 1@exp 50 script fix_boy@fix_Repair}
{15}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 30&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@exp 50 script fix_boy@fix_Repair}
{16}{}{PID_SHARP_SPEAR@Заточка копья кремнем от фирмы "Морлис" позволит разрубать врагов им как алебардой.@SK_OUTDOORSMAN 30@SK_MELEE_WEAPONS 40&SK_REPAIR 20&SK_OUTDOORSMAN 40@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@exp 50 script fix_boy@fix_Repair}
{17}{}{PID_SHARPENED_POLE@Вжик-вжик, готово!@@SK_OUTDOORSMAN 20@PID_FIREWOOD 1@PID_KNIFE 1@PID_SHARPENED_POLE 1@exp 10 }
{18}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@exp 50 script fix_boy@fix_Repair}
{19}{}{PID_WRENCH@Найдите железку подходящего размера и выпилите из неё нечто, чем можно было бы откручивать гайки.@@SK_REPAIR 50@PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_SLEDGEHAMMER 1|PID_SUPER_TOOL_KIT 1@PID_WRENCH 1@exp 50 script fix_boy@fix_Repair}
{20}{}{PID_KNIFE@Заточите железяку о камень, обмотайте конец какой-нибудь тряпкой. Готово, можно идти похвастаться родителям.@@SK_OUTDOORSMAN 20@PID_METAL_TRASH 1&PID_RAGS 1@@PID_KNIFE 1@exp 50 script fix_boy@fix_Repair}
{21}{}{PID_CLUB@Отломайте нахрен минимум треть этой палки, забейте камнем в один конец какой-нибудь утяжелитель. Отломаный кусок можно притарабанить в качестве дополнительной рукояти. Готово, можно пойти проломить кому-нибудь черепушку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40&SK_REPAIR 30@PID_SHARPENED_POLE 1&PID_PUMP_PARTS 1@PID_ROCK 1@PID_CLUB 1@exp 50 script fix_boy@fix_Repair}
{22}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_KNIFE 1@PID_SHIV 1@exp 50 script fix_boy@fix_Repair}
{23}{}{PID_THROWING_KNIFE@Сбалансируйте и дополнительно заточите эту железку.@SK_THROWING 40@SK_THROWING 50&SK_REPAIR 30@PID_KNIFE 1&PID_FLINT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_THROWING_KNIFE 1@exp 50 script fix_boy@fix_Repair}
{24}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 30@PID_ROT_GUT 1&PID_RAGS 1&PID_BROC_FLOWER 5@@PID_MOLOTOV_COCKTAIL 1@exp 50 script fix_boy@fix_Science}
{25}{}{PID_MOLOTOV_COCKTAIL@Нет огнемёта? Не беда, всегда можно найти способ доставить пламя до противника.@SK_SCIENCE 20@SK_SCIENCE 30&SK_REPAIR 30@PID_BOTTLE_GLASS 1&PID_RAGS 1&PID_FLAMETHROWER_FUEL 1@@PID_MOLOTOV_COCKTAIL 1@exp 50 script fix_boy@fix_Science}
{26}{}{PID_SCOPED_HUNTING_RIFLE@Для простенького прицела сойдут и линзы из чьих-нибудь очков, главное - чётко следовать инструкциям.@SK_SMALL_GUNS 50@SK_REPAIR 60&SK_SMALL_GUNS 60&SK_SCIENCE 60@PID_HUNTING_RIFLE 1&PID_TUBE 1&PID_SPECTACLES 2&PID_PUMP_PARTS 1@PID_GUNS_AND_BULLETS 1&PID_SUPER_TOOL_KIT 1@PID_SCOPED_HUNTING_RIFLE 1@exp 100 script fix_boy@fix_Advanced}
{28}{}{PID_SHOTGUN@Найдите две трубы более-менее подходящего диаметра, изготовьте к ним приклад и простенький спусковой механизм.@SK_SMALL_GUNS 50@SK_SMALL_GUNS 80&SK_REPAIR 80@PID_SHOTGUN_SHELLS 20&PID_TUBE 2&PID_FIREWOOD 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 2@PID_SUPER_TOOL_KIT 1&PID_COMBAT_KNIFE 1&PID_GUNS_AND_BULLETS 1@PID_SHOTGUN 1@exp 150 script fix_boy@fix_Repair}
{29}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 20@SK_REPAIR 30@PID_SHOTGUN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SAWED_OFF_SHOTGUN 1@exp 100 script fix_boy@fix_Repair}
{31}{}{PID_DESERT_EAGLE_EXT_MAG@С переделкой магазина придётся помучиться, но она сэкономит несколько драгоценных секунд в бою.@SK_REPAIR 60@SK_REPAIR 80@PID_DESERT_EAGLE 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 60 script fix_boy@fix_Advanced}
{32}{}{PID_SPRINGER_RIFLE@Главной проблемой будет найти трубу подходящего диаметра, а спусковой механизм вы соорудить сумеете.@SK_SMALL_GUNS 50@SK_REPAIR 40&SK_OUTDOORSMAN 40&SK_SMALL_GUNS 50@PID_TUBE 1&PID_FIREWOOD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SPRINGER_RIFLE 1@exp 100 script fix_boy@fix_Repair}
{33}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@SK_SMALL_GUNS 50@SK_OUTDOORSMAN 30&SK_REPAIR 40@PID_FIREWOOD 1&PID_METAL_TRASH 1@@PID_ZIP_GUN 1@exp 75 script fix_boy@fix_Repair}
{34}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_REPAIR 90@SK_REPAIR 100&SK_SCIENCE 60@PID_FLAMETHROWER_FUEL 5&PID_METAL_TRASH 3&PID_TUBE 1&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMER 1@exp 150 script fix_boy@fix_HighTech}
{35}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_CHEMICALS 2&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMETHROWER_FUEL 10@exp 50 script fix_boy@fix_Advanced}
{36}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 80@PID_FLAMETHROWER_FUEL 1&PID_ROT_GUT 1&PID_CHEMICALS 1&PID_PUMP_PARTS 1@PID_CHEMISTRY_MANUAL 1@PID_FLAMETHROWER_FUEL 10@exp 50 script fix_boy@fix_Advanced}
{37}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_RAGS 1@PID_ROCK 1@PID_HEALING_POWDER 1@exp 50 script fix_boy@fix_Science}
{38}{}{PID_ANTIDOTE@Это будет скорей самовнушением. @SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 40&SK_DOCTOR 20@PID_BOOZE 1&PID_SCORPION_TAIL 1@PID_LIGHTER 1@PID_ANTIDOTE 1@exp 50 script fix_boy@fix_Science}
{39}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле.@SK_LOCKPICK 50@SK_LOCKPICK 70@PID_METAL_TRASH 1&PID_PUMP_PARTS 1&PID_GECKO_PELT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_LOCKPICKS 1@exp 50 script fix_boy@fix_Repair}
{40}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами!@SK_LOCKPICK 70@SK_LOCKPICK 100@PID_LOCKPICKS 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_EXP_LOCKPICK_SET 1@exp 100 script fix_boy@fix_Repair}
{41}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Схема простейшего приёмника в каждом номере "Электроники Дина"!@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1|PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@exp 100 }
{42}{}{PID_FIRST_AID_KIT@Бинты, спирт для промывки ран и другие полезные вещи в сумке из кожи многострадального гекко.@SK_FIRST_AID 50@SK_DOCTOR 50&SK_FIRST_AID 60&SK_SCIENCE 20@PID_RAGS 5&PID_BOOZE 1&PID_ANTIDOTE 1&PID_GECKO_PELT 1&PID_POCKET_LINT 1@@PID_FIRST_AID_KIT 1@exp 150 }
{43}{}{PID_RADIO@Почините радио с использованием деталей со старых микросхем.@SK_REPAIR 50@SK_REPAIR 60@PID_VIC_RADIO 1&PID_V15_COMPUTER_PART 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_RADIO 1@exp 100 script fix_boy@fix_Repair}
{44}{}{PID_TNT@Вливайте азотную кислоту в толуол, постоянно нагревая, осадок просушите и поместите в какую-нибудь банку.@SK_SCIENCE 80@SK_SCIENCE 100@PID_CHEMICALS 2&PID_BOTTLE_FULL 1&PID_PUMP_PARTS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_TNT 1@exp 100 script fix_boy@fix_Science}
{45}{}{PID_FRAG_GRENADE@Поместите взрывчатое вещевство в осколочную рубашку и придумайте простенький взрыватель.@SK_REPAIR 80@SK_REPAIR 100@PID_PUMP_PARTS 1&PID_METAL_TRASH 1&PID_TNT 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_FRAG_GRENADE 1@exp 130 script fix_boy@fix_Advanced}
{46}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 90@SK_SCIENCE 110&SK_OUTDOORSMAN 50@PID_MEAT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_CHEMISTRY_MANUAL 1@PID_NITROGLYCERIN 1@exp 150 script fix_boy@fix_Science}
{47}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@SK_TRAPS 100@SK_OUTDOORSMAN 30&SK_SCIENCE 60&SK_TRAPS 120&SK_REPAIR 100@PID_NITROGLYCERIN 2&PID_HEALING_POWDER 2&PID_FIREWOOD 1&PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_DYNAMITE 1@exp 200 script fix_boy@fix_HighTech}
{48}{}{PID_GUNPOWDER@Используйте кислоту для получения калийной селитры, смешайте 6 частей селитры с 1 частью угля и 1 серы.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 50&SK_SCIENCE 80@PID_MINERAL 1&PID_CHEMICALS 1&PID_FIREWOOD 1@PID_CHEMISTRY_MANUAL 1&PID_ROCK 1@PID_GUNPOWDER 1@exp 100 script fix_boy@fix_Science}
{49}{}{PID_HEXOGEN@Получите нитрат аммония смешиванием собственной мочи с азотной кислотой и выпариванием. Добавьте толчёный буффаут. Залейте второй частью кислоты, охлаждайте, процедите осадок.@SK_SCIENCE 100@SK_SCIENCE 120&SK_OUTDOORSMAN 60@PID_BUFFOUT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 2&PID_RAGS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_HEXOGEN 1@exp 150 script fix_boy@fix_Science}
{50}{}{PID_PLASTIC_EXPLOSIVES_DULL@Найдите в мусоре какой-нибудь пластик, нагрейте его до плавления и вмешивайте в него порошок гексогена. Всё, теперь он удобен для хранения.@SK_SCIENCE 120@SK_OUTDOORSMAN 60&SK_REPAIR 60@PID_PUMP_PARTS 2&PID_HEXOGEN 1@PID_LIGHTER 1@PID_PLASTIC_EXPLOSIVES_DULL 1@exp 100 script fix_boy@fix_Advanced}
{51}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор из запчастей и старого радио.@SK_REPAIR 100@SK_REPAIR 130&SK_TRAPS 120@PID_PLASTIC_EXPLOSIVES_DULL 1&PID_V15_COMPUTER_PART 1&PID_RADIO 1@PID_MULTI_TOOL 1&PID_CHEMISTRY_MANUAL 1|PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_PLASTIC_EXPLOSIVES 1@exp 200 script fix_boy@fix_HighTech}
{52}{}{PID_MINE@Высыпьте гексоген в какую-нибудь старую банку, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@SK_TRAPS 80@SK_TRAPS 130&SK_SCIENCE 100&SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_HEXOGEN 1&PID_PUMP_PARTS 2&PID_SHOTGUN_SHELLS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_MINE 1@exp 200 script fix_boy@fix_HighTech}
{54}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@SK_FIRST_AID 30@SK_FIRST_AID 70&SK_SCIENCE 70@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 1&PID_BOOZE 1&PID_HEALING_POWDER 2@PID_LIGHTER 1&PID_FIRST_AID_BOOK 1&PID_CHEMISTRY_MANUAL 1&PID_FIRST_AID_KIT 1@PID_STIMPAK 1@exp 50 script fix_boy@fix_Science}
{55}{}{PID_MAUSER_SMG@В одном из номеров журнала "Пушки и пули" была опубликована схема автоматического Маузера М712 калибра 7,62. Изучив её, вы поняли, что 9мм Маузер можно было бы переделать подобным образом.@SK_SMALL_GUNS 50@SK_REPAIR 50@PID_9MM_MAUSER 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1|PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_MAUSER_SMG 1@exp 100 script fix_boy@fix_Repair}
{56}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_ROCK 1@PID_AXE 1@exp 50 script fix_boy@fix_Repair}
{57}{}{PID_MEDICAL_SUPPLIES@Алкоголь для дезинфекции, лечебный порошок для лечения - и вот у вас уже неплохой комплект для оказания первой помощи в условиях пустоши. Эффективность близка к волшебным микстурам времён Дикого Запада, но от укусов и ран помогает.@SK_FIRST_AID 20@SK_FIRST_AID 30@PID_BOOZE 1&PID_HEALING_POWDER 1@@PID_MEDICAL_SUPPLIES 3@exp 50 script fix_boy@fix_Science}
{62}{}{PID_DEFIB@Стандартный реанимационный набор для восстановления жизнедеятельности. Можно собрать, имея нужные познания в медицине@SK_DOCTOR 30@SK_FIRST_AID 50&SK_SCIENCE 40&SK_DOCTOR 70&SK_REPAIR 30@PID_METAL_TRASH 2&PID_SMALL_ENERGY_CELL 5&PID_PUMP_PARTS 2&PID_DOCTORS_BAG 1&PID_STIMPAK 2&PID_V15_COMPUTER_PART 1@PID_SUPER_TOOL_KIT 1@PID_DEFIB 1@exp 300 script fix_boy@fix_HighTech}
{63}{}{PID_LASER_PISTOL@Энергетическое оружие. Не очень мощное, но относительно простое в производстве.@SK_REPAIR 60@SK_REPAIR 100&SK_SCIENCE 120&SK_ENERGY_WEAPONS 80@PID_METAL_TRASH 2&PID_SMALL_ENERGY_CELL 5&PID_PUMP_PARTS 2&PID_SPECTACLES 1&PID_ZIP_GUN 1&PID_V15_COMPUTER_PART 2@PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_LASER_PISTOL_LOW 1@exp 500 script fix_boy@fix_HighTech}
{64}{}{PID_NEEDLER_PISTOL@Пистолет, стреляющий шприцами-дротиками. Вполне можно изготовить из подручных материалов.@SK_REPAIR 60@SK_REPAIR 100&SK_SCIENCE 120&SK_SMALL_GUNS 60@PID_METAL_TRASH 2&PID_HN_NEEDLER_CARTRIDGE 5&PID_PUMP_PARTS 3&PID_ZIP_GUN 1&PID_V15_COMPUTER_PART 1@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_NEEDLER_PISTOL 1@exp 500 script fix_boy@fix_HighTech}
{65}{}{PID_HN_NEEDLER_CARTRIDGE@Шприцы-дротики для пистолета-инъектора делаются из твердого пластика. Довольно просто. Нужно только заполнить их какими-нибудь химикатами.@SK_REPAIR 20@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_PUMP_PARTS 5@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_LIGHTER 1@PID_HN_NEEDLER_CARTRIDGE 10@exp 200 script fix_boy@fix_Advanced}
{66}{}{PID_NEED_CART_POISON@Картриджи для инъектора можно заполнить ядом радскорпионов. Измельчить 2 хвоста радскорпиона, залить растворителем, дать настояться несколько часов. Затем выпарить для достижения большей концентрации и заправить картриджи.@SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 100&SK_SMALL_GUNS 60@PID_CHEMICALS 1&PID_HN_NEEDLER_CARTRIDGE 10&PID_METAL_TRASH 1&PID_SCORPION_TAIL 2@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_NEED_CART_POISON 10@exp 250 script fix_boy@fix_Advanced}
{67}{}{PID_HYPO_POISON@Сильнейший нейротоксин, который в малых количествах содержится в ядовитом жале радскорпионов можно извлечь методом кислотно-щелочной экстракции.@SK_SCIENCE 80@SK_SCIENCE 140@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 1&PID_BOTTLE_GLASS 2&PID_SCORPION_TAIL 8@PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_KNIFE 1@PID_HYPO_POISON 1@exp 350 script fix_boy@fix_Science}
{68}{}{PID_NEED_CART_NT@Картриджи иньектора можно заполнить опаснейшим нейротоксином... Нужно только найти нейротоксин. @SK_SCIENCE 50@SK_REPAIR 60&SK_SCIENCE 80&SK_SMALL_GUNS 60@PID_HYPO_POISON 1&PID_HN_NEEDLER_CARTRIDGE 10@@PID_NEED_CART_NT 10@exp 400 script fix_boy@fix_Advanced}
{69}{}{PID_PART_OF_ROPE@Возьмите что-нибудь острое и разрежьте веревку на несколько кусков. @SK_MELEE_WEAPONS 10@SK_MELEE_WEAPONS 20@PID_ROPE 1@PID_KNIFE 1|PID_SWITCHBLADE 1|PID_LIL_JESUS_WEAPON 1|PID_WAKIZASHI_BLADE 1|PID_AXE 1@PID_PART_OF_ROPE 10@exp 10 script fix_boy@fix_Repair}
{70}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@@@PID_PART_OF_ROPE 20@@PID_ROPE 1@exp 30 script fix_boy@fix_Repair}
{71}{}{PID_ANTIDOTE_2@Мощное противоядие, нейтрализующее действие нейротоксина. Можно сделать, имея образец токсина.@SK_SCIENCE 60@SK_SCIENCE 100@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 3&PID_BOTTLE_GLASS 2&PID_HYPO_POISON 1@PID_CHEMISTRY_MANUAL 1&PID_LIGHTER 1@PID_ANTIDOTE_2 3@exp 450 script fix_boy@fix_Science}
{72}{}{PID_HANDCUFFS@В довоенном журнале про оружие вы нашли статью об устройстве наручников. Не так уж сложно сделать, если немного рабираться в ремонте и замках.@SK_REPAIR 80@SK_SCIENCE 60&SK_REPAIR 100&SK_LOCKPICK 100@PID_METAL_TRASH 3&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_WELDING 1@PID_HANDCUFFS 1@exp 100 script fix_boy@fix_Repair}
{73}{}{PID_HANDCUFFS@Сломанные наручники можно восстановить и переделать под новый ключ, если под рукой есть нужны инструменты@SK_REPAIR 40@SK_REPAIR 60&SK_LOCKPICK 40@PID_METAL_TRASH 1&PID_BROKEN_CUFFS 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_HANDCUFFS 1@exp 50 script fix_boy@fix_Repair}
{74}{}{PID_COLT@Листая довоенный журнал про оружие, вы нашли схему Кольта М1911. С немалым удивлением, вы обнаружили, что под него довольно просто переделать обычный 10мм пистолет!@SK_REPAIR 80@SK_REPAIR 100&SK_SMALL_GUNS 120@PID_10MM_PISTOL 1&PID_METAL_TRASH 1&PID_TUBE 1&PID_PUMP_PARTS 2&PID_45_CALIBER_AMMO 7@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_COLT 1@exp 450 script fix_boy@fix_Advanced}
{75}{}{PID_MUMARMOR@Специализированная броня для супермутантов. Укрепляет их и без того мощное тело.@SK_REPAIR 80@SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_METAL_TRASH 8&PID_GOLDEN_GECKO_PELT 4&PID_PUMP_PARTS 2&PID_WELDING 1&PID_IRON_PLATE 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUMARMOR 1@exp 550 script fix_boy@fix_Advanced}
{76}{}{PID_MUJACKET@Кожанная куртка для мутантов. Технология производста почти не отличается от обычной, но материала уходит в два раза больше.@SK_OUTDOORSMAN 40@SK_REPAIR 80&SK_OUTDOORSMAN 80@PID_GECKO_PELT 4&PID_GOLDEN_GECKO_PELT 8&PID_POCKET_LINT 4&PID_CHEMICALS 2@PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MUJACKET 1@exp 250 script fix_boy@fix_Advanced}
{77}{}{PID_SOUND_BLASTER@В довоенном журнале вы нашли статью об оглушающем акустическом оружии. Схема прилагается. Выглядит не слишком сложно.@SK_BIG_GUNS 40@SK_SCIENCE 100&SK_BIG_GUNS 40&SK_REPAIR 80@PID_METAL_TRASH 8&PID_TUBE 1&PID_V15_COMPUTER_PART 2&PID_SPRINGER_RIFLE 1&PID_SMALL_ENERGY_CELL 10&PID_IRON_DETALS 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_GUNS_AND_BULLETS 1@PID_SOUND_BLASTER 1@exp 600 script fix_boy@fix_HighTech}
{78}{}{PID_SANDROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава.@@SK_OUTDOORSMAN 40@PID_RAGS 5&PID_POCKET_LINT 2&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_SANDROBE 1@exp 150 script fix_boy@fix_Repair}
{79}{}{PID_CURED_LEATHER_ARMOR_MK_II@Хотите ещё более плотную куртку? Пожалуйста. Только учтите, что она не такая просторная, хоть и выглядит достаточно стильно.@SK_REPAIR 60&SK_OUTDOORSMAN 60@SK_OUTDOORSMAN 90&SK_REPAIR 75@PID_METAL_TRASH 2&PID_POCKET_LINT 2&PID_CURED_LEATHER_ARMOR 1&PID_IRON_PLATE 1@PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR_MK_II 1@exp 185 script fix_boy@fix_Advanced}
{80}{}{PID_ONEHAND_ROCKET_LAUNCHER@Найдите трубу более-менее подходящего диаметра, изготовьте рукоять и простенький спусковой механизм. Соберите всё вместе и надейтесь, что оно будет работать.@SK_BIG_GUNS 80@SK_BIG_GUNS 130&SK_SCIENCE 50&SK_REPAIR 100@PID_FIREWOOD 2&PID_PUMP_PARTS 2&PID_METAL_TRASH 6&PID_TUBE 1@PID_SUPER_TOOL_KIT 1&PID_COMBAT_KNIFE 1&PID_GUNS_AND_BULLETS 1@PID_ONEHAND_ROCKET_LAUNCHER 1@exp 240 script fix_boy@fix_Repair}
{81}{}{PID_LOCKER_LOW@Самый просто навесной замок. Проще некуда.@SK_REPAIR 50&SK_LOCKPICK 30@SK_REPAIR 60&SK_LOCKPICK 40@PID_METAL_TRASH 5@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LOCKER_LOW 1@exp 150 script fix_boy@fix_Repair}
{82}{}{PID_LOCKER_MED@Замок среднего уровня. Может от кого-то и спасет.@SK_REPAIR 90&SK_LOCKPICK 50@SK_REPAIR 100&SK_LOCKPICK 60@PID_METAL_TRASH 10@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LOCKER_MED 1@exp 250 script fix_boy@fix_Repair}
{83}{}{PID_LOCKER_HARD@Хех, куда же такой сейф ставить?@SK_REPAIR 140&SK_LOCKPICK 70@SK_REPAIR 150&SK_LOCKPICK 80@PID_METAL_TRASH 15@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LOCKER_HARD 1@exp 350 script fix_boy@fix_Repair}
{84}{}{PID_KNIFE_P@Выдавите немного яда из хвоста скорпиона на нож, и ваш противник будет повержен ядом.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_KNIFE 1&PID_SCORPION_TAIL 1@@PID_KNIFE_P 1@exp 100 script fix_boy@fix_Repair}
{85}{}{PID_SPEAK_P@Острое как бритва, и ядовитое как опасный враг путешественника@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SPEAR 1&PID_SCORPION_TAIL 1@@PID_SPEAK_P 1@exp 100 script fix_boy@fix_Repair}
{86}{}{PID_MKNIFE_P@Метательный и ядовитый. Гремучая смесь.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 1&PID_THROWING_KNIFE 1@@PID_MKNIFE_P 1@exp 100 script fix_boy@fix_Repair}
{87}{}{PID_СKNIFE_P@Верный боевой нож. Теперь с ядом! Ограниченная партия!@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 1&PID_COMBAT_KNIFE 1@@PID_CKNIFE_P 1@exp 100 script fix_boy@fix_Repair}
{88}{}{PID_TRAP_ELECTRIC@Электрическая ловушка. Как это ни странно,но она бьет током.@SK_TRAPS 60&SK_SCIENCE 50@SK_TRAPS 70&SK_SCIENCE 60@PID_METAL_TRASH 5&PID_SMALL_ENERGY_CELL 5@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_ELECTRIC 1@exp 150 script fix_boy@fix_Repair}
{89}{}{PID_TRAP_FIRE_BREATH@Дыхание гекко. Выпускает струю огня на незатейливого путника.@SK_REPAIR 50&SK_LOCKPICK 30@SK_REPAIR 60&SK_LOCKPICK 40@PID_METAL_TRASH 5&PID_FLAMETHROWER_FUEL 3@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_FIRE_BREATH 1@exp 150 script fix_boy@fix_Repair}
{90}{}{PID_TRAP_KNIFES@Ловушка ножи, просто засунте в ящик или дверь.@SK_REPAIR 50&SK_LOCKPICK 30@SK_REPAIR 60&SK_LOCKPICK 40@PID_METAL_TRASH 5@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_KNIFES 1@exp 150 script fix_boy@fix_Repair}
{91}{}{PID_TRAP_CANISTER_SHOT@Когда вы еще могли мечтать о таком чудном применении этой бесполезной вещи?@SK_REPAIR 50&SK_TRAPS 30@SK_REPAIR 60&SK_TRAPS 40@PID_BBS 100&PID_GUNPOWDER 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_CANISTER_SHOT 1@exp 150 script fix_boy@fix_Repair}
{92}{}{PID_TRAP_STUNNER@Електрошоккер еще одно отличное средство вырбить незваных гостей. Пятизарядный.@SK_TRAPS 90&SK_SCIENCE 90@SK_TRAPS 100&SK_SCIENCE 100@PID_METAL_TRASH 5&PID_SMALL_ENERGY_CELL 10@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_STUNNER 1@exp 150 script fix_boy@fix_Repair}
{93}{}{PID_TRAP_SLEDGE_HAMMER@Кувалда на двери - отличный спобок вырубить воришку.@SK_REPAIR 50&SK_TRAPS 50@SK_REPAIR 60&SK_TRAPS 60@PID_SLEDGEHAMMER 1&PID_ROPE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_SLEDGE_HAMMER 1@exp 150 script fix_boy@fix_Repair}
{94}{}{PID_TRAP_POISON_BLADE@Отравленые ножи - приятный сюрприз для нежданых гостей.@SK_REPAIR 50&SK_TRAPS 70@SK_REPAIR 60&SK_TRAPS 80@PID_TRAP_KNIFES 1&PID_RADSCORPION_PARTS 3@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_POISON_BLADE 1@exp 150 script fix_boy@fix_Repair}
{95}{}{PID_TRAP_ITEM_BREAKER@Ловушка уничтожающая все вещи в ящике. Будьте осторожней.@SK_TRAPS 150&SK_SCIENCE 130@SK_TRAPS 160&SK_SCIENCE 140@PID_METAL_TRASH 5@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_ITEM_BREAKER 1@exp 150 script fix_boy@fix_Repair}
{96}{}{PID_TRAP_STAKE@Колья, почти как в Рембо.@SK_TRAPS 50&SK_OUTDOORSMAN 30@SK_TRAPS 60&SK_OUTDOORSMAN 40@PID_SHARPENED_POLE 1@PID_MULTI_TOOL 1@PID_TRAP_STAKE 1@exp 150 script fix_boy@fix_Repair}
{97}{}{PID_JEWELERY@Ювелирная заготовка@SK_SCIENCE 20&SK_REPAIR 20&SK_OUTDOORSMAN 80@SK_SCIENCE 40&SK_REPAIR 40&SK_OUTDOORSMAN 100@PID_GOLD_NUGGET 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_JEWELERY 1@exp 200 }
{98}{}{PID_WED_RING@Изумительное женское обручальное кольцо@SK_SCIENCE 20&SK_REPAIR 20&SK_OUTDOORSMAN 80@SK_SCIENCE 40&SK_REPAIR 40&SK_OUTDOORSMAN 120@PID_JEWELERY 1&PID_RUBIN 1@PID_MULTI_TOOL 1@PID_WED_RING 1@exp 200 }
{1301}{}{PID_SAWGUN_LOW@Пушка пила.Собираем раму, устанавливаем движок, натягиваем цепь и передаточный механизм для катапульты.@SK_BIG_GUNS 40@SK_REPAIR 120&SK_SCIENCE 60&SK_BIG_GUNS 40@PID_METAL_TRASH 8&PID_PUMP_PARTS 3&PID_TUBE 2&PID_MOTOR 1&PID_CHAIN 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SAWGUN_LOW 1@exp 350 script fix_boy@fix_Advanced}
{1302}{}{PID_DRUM_GUN_LOW@Барабанная пушка.Собираем затворный механизм, барабанный магазин, автовзвод и надеемся, что это не рассыпется при первом выстреле.@SK_SMALL_GUNS 60@SK_REPAIR 60&SK_SCIENCE 40@PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_TUBE 1&PID_IRON_DETALS 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_DRUM_GUN_LOW 1@exp 120 script fix_boy@fix_Repair}
{1303}{}{PID_SNIPER_GUN_LOW@Дырокол.Высверливаем ствол, жестко скрепляем раму приклада, присоединяем сошки.@SK_SMALL_GUNS 80@SK_REPAIR 90@PID_METAL_TRASH 4&PID_PUMP_PARTS 1&PID_TUBE 3@PID_MULTI_TOOL 1&PID_WELDING 1@PID_SNIPER_GUN_LOW 1@exp 230 script fix_boy@fix_Repair}
{1304}{}{PID_PLASMA_SMG_LOW@Излучатель, отражатели, камера для энергоячеек, вот вроде и все.@SK_ENERGY_WEAPONS 80@SK_REPAIR 60&SK_SCIENCE 70@PID_V15_COMPUTER_PART 2&PID_METAL_TRASH 2&PID_PUMP_PARTS 3&PID_TUBE 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_PLASMA_SMG_LOW 1@exp 200 script fix_boy@fix_Advanced}
{1305}{}{PID_SHOTPISTOL_LOW@Двуствольный пистолет.Берем стволы от дробовика, обрезаем, соединяем с пистолетной рукоятьсю, вуаля франкенштейн готов@SK_SMALL_GUNS 60@SK_REPAIR 70@PID_SHOTGUN 1&PID_10MM_PISTOL 1@PID_MULTI_TOOL 1@PID_SHOTPISTOL_LOW 1@exp 100 }
{1306}{}{PID_REVOLVER_LOW@Самодельный револьвер.Барабан, курок и ствол. Ничего сложного@SK_SMALL_GUNS 50@SK_SMALL_GUNS 50&SK_REPAIR 40@PID_PUMP_PARTS 2&PID_TUBE 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_REVOLVER_LOW 1@exp 150 script fix_boy@fix_Repair}
{1307}{}{PID_PISTOL_LOW@Самозарядный пистолет.проблема в механизме заряжания, из подручного хлама ничего получше не сделать@SK_SMALL_GUNS 30@SK_REPAIR 60@PID_PUMP_PARTS 2&PID_TUBE 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_PISTOL_LOW 1@exp 100 script fix_boy@fix_Repair}
{1308}{}{PID_REV_RIFLE_LOW@Револьверная винтовка, проще говоря револьвер с длинным стволом и переработанной рукоятью.@SK_SMALL_GUNS 50@SK_REPAIR 60@PID_PUMP_PARTS 2&PID_TUBE 1&PID_METAL_TRASH 1&PID_REVOLVER_LOW 1@PID_MULTI_TOOL 1@PID_REV_RIFLE_LOW 1@exp 150 script fix_boy@fix_Repair}
{1309}{}{PID_BIGGUN_LOW@Большая пушка.@SK_BIG_GUNS 40@SK_REPAIR 40@PID_PUMP_PARTS 1&PID_TUBE 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_BIGGUN_LOW 1@exp 100 script fix_boy@fix_Repair}
{1330}{}{PID_10mm_LOW@Выпарить грибы, засыпать получившийся порошок в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_PB_FOR_AMMO 1&PID_MUSH_LOW 2@PID_LIGHTER 1@PID_10mm_LOW 20@exp 50 script fix_boy@fix_Science}
{1331}{}{PID_044mag_LOW@Выпарить грибы, засыпать получившийся порошок в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_PB_FOR_AMMO 1&PID_MUSH_LOW 2&PID_FIREWOOD 1@PID_LIGHTER 1@PID_044mag_LOW 15@exp 50 script fix_boy@fix_Science}
{1332}{}{PID_14mm_LOW@Засыпать порох в гильзу, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_GUNPOWDER 1&PID_FIREWOOD 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_14mm_LOW 10@exp 50 script fix_boy@fix_Science}
{1333}{}{PID_12g_LOW@Выпарить грибы, засыпать получившийся порошок в картуш из ветоши, насыпать обломков гвоздей.@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_MUSH_LOW 2&PID_RAGS 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_12g_LOW 20@exp 50 script fix_boy@fix_Science}
{1334}{}{PID_223_LOW@Засыпать порох в старые гильзы, вставить пулю@SK_SMALL_GUNS 30@SK_REPAIR 40@PID_METAL_TRASH 2&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_223_LOW 15@exp 50 script fix_boy@fix_Science}
{1335}{}{PID_CUENCELL_LOW@извлекаем радиоактивные элементы, естанавливаем их в оболочку, добавляем реагенты, обматываем фольгой и закрываем в корпус@SK_SCIENCE 120@SK_REPAIR 80@PID_RAD_LOW 1&PID_METAL_TRASH 2@PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_CUENCELL_LOW 20@exp 150 script fix_boy@fix_Science2}
{1336}{}{PID_POLE_DART_LOW@выстругиваем небольшие деревянные дротики@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 40@PID_FIREWOOD 1@PID_KNIFE 1@PID_POLE_DART_LOW 20@exp 20 }
{1338}{}{PID_MIRELUK_ARMOR@Панцири болотников скрепляются наслоением так, чтобы не лишать одевшего подвижности.@SK_REPAIR 20&SK_OUTDOORSMAN 80@SK_REPAIR 80&SK_OUTDOORSMAN 120&SK_SCIENCE 60@PID_POCKET_LINT 1&PID_MIRELUK_SHELL 6&PID_LEATHER_ARMOR 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_BALL_DEAD 1@exp 250 script fix_boy@fix_Repair}
{1339}{}{PID_MANTIS_ARMOR@Скрепляем хитиновые пластины подобием чешуи, панцирь болотника идет на нагрудник.@SK_OUTDOORSMAN 30&SK_REPAIR 20@SK_OUTDOORSMAN 80&SK_REPAIR 60@PID_POCKET_LINT 1&PID_MIRELUK_SHELL 1&PID_MANTIS_SHELL 4@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MANTIS_ARMOUR 1@exp 100 script fix_boy@fix_Repair}
{1340}{}{PID_SMOKE_GUN_LOW@Соединяем различные старые испорченные детали от старых пистолетов, понимание как сделать такую вещь приходит только после первого убийства.@SK_SMALL_GUNS 70&KILL_MEN 1@SK_REPAIR 80@PID_PUMP_PARTS 2&PID_TUBE 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_SMOKE_GUN_LOW 1@exp 150 }
{1341}{}{PID_AUTOGUN_LOW@Берем обычный пистолет, модернизируем затворный механизм, для автовзвода, закрываем корпусом. Громоздко, но работает.@SK_SMALL_GUNS 30@SK_REPAIR 80&SK_SCIENCE 100@PID_PUMP_PARTS 2&PID_TUBE 1&PID_METAL_TRASH 1&PID_10MM_PISTOL 1@PID_MULTI_TOOL 1&PID_WELDING 1@PID_AUTOGUN_LOW 1@exp 120 script fix_boy@fix_Advanced}
{1342}{}{PID_SPEARTHROWER1_LOW@Пара пружин, рычаги и рама@SK_REPAIR 50@SK_REPAIR 50&SK_SCIENCE 30@PID_PUMP_PARTS 2@PID_MULTI_TOOL 1@PID_SPEARTHROWER1 1@exp 120 script fix_boy@fix_Repair}
{1343}{}{PID_SPEARTHROWER2_LOW@Баллон, корпус, ручная помпа.@SK_SCIENCE 80@SK_SCIENCE 80&SK_REPAIR 60@PID_PUMP_PARTS 2&PID_OXYGEN_TANK 1@PID_MULTI_TOOL 1@PID_SPEARTHROWER2 1@exp 220 script fix_boy@fix_Repair}
{1344}{}{PID_GUNPOWDER@Используйте кислоту как катализатор для превращения толченых выпаренных грибов в гранулы, по характеристикам не уступающим обычному пороху.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 50&SK_SCIENCE 80@PID_FIREWOOD 1&PID_MUSH_LOW 6@PID_CHEMISTRY_MANUAL 1&PID_ROCK 1&PID_LIGHTER 1&PID_CHEMICALS 1@PID_GUNPOWDER 1@exp 50 script fix_boy@fix_Science}
{1345}{}{PID_PB_FOR_AMMO@Нехитрым приспособлением можно быстро клепать болванки гильз и заготовки для пуль.@SK_SMALL_GUNS 30@SK_REPAIR 60@PID_METAL_TRASH 1@PID_LIGHTER 1&PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 1@exp 50 script fix_boy@fix_Science}
{1346}{}{PID_KOSYAK@Разотрите камнем высушенные на солнце ингредиенты, добавьте секретный ингридиент.@PE_FLOWER_CHILD 1@SK_OUTDOORSMAN 30&PE_FLOWER_CHILD 1@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_RAGS 1@@PID_KOSYAK 1@exp 5 script fix_boy@fix_Science}
